[package]
name = "nylon-command"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
service-manager = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }