[package]
name = "nylon-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
nylon-types = { path = "../nylon-types" }
nylon-error = { path = "../nylon-error" }
serde_json = { workspace = true }
serde = { workspace = true }
pingora = { workspace = true }