header_selector: x-nylon-proxy

# plugins:
#   - name: go-users
#     type: ffi
#     file: ./examples/plugin_sdk.so
#     entry:
#       - sdk_handle_request
#     life_cycle:
#       setup: true
#       shutdown: true

services:
  - name: http-service
    service_type: http
    algorithm: round_robin # Options: round_robin, random, consistent, weighted
    endpoints:
      - ip: 127.0.0.1
        port: 3000
        weight: 10 # Optional
      - ip: 127.0.0.1
        port: 3001
        weight: 1 # Optional

  - name: ffi-service
    service_type: plugin
    plugin:
      name: ffi-plugin
      entry: "sdk_handle_request"
      payload:
        debug: true