header_selector: x-nylon-proxy

# NATS messaging configuration (optional)
messaging:
  - name: default
    servers:
      - nats://localhost:4222
    # Optional: override defaults
    # request_timeout_ms: 5000
    # max_inflight: 1024

plugins:
  # FFI Plugin (in-process, low latency)
  - name: plugin_sdk
    type: ffi
    file: ./target/examples/go/plugin_sdk.so
    config:
      debug: true
  
  # NATS Plugin (distributed, scalable) - uncomment to use
  - name: plugin_nats
    type: messaging
    messaging: default
    group: my-workers
    config:
      debug: true
    # Optional: per-phase overrides
    # per_phase:
    #   request_filter:
    #     timeout_ms: 8000

services:
  # Http service
  - name: app-service
    service_type: http
    algorithm: round_robin # Options: round_robin, random, consistent, weighted
    endpoints:
      - ip: 127.0.0.1
        port: 3001
      # - ip: 127.0.0.1
      #   port: 3002
    health_check:
      enabled: false
      path: /health
      interval: 3s
      timeout: 1s
      healthy_threshold: 2
      unhealthy_threshold: 2

  # WebSocket and streaming via plugin
  - name: ws-service
    service_type: plugin
    plugin:
      name: plugin_sdk
      entry: ws

  - name: stream-service
    service_type: plugin
    plugin:
      name: plugin_sdk
      entry: stream

  # Static assets / SPA
  - name: static
    service_type: static
    static:
      root: ./examples/static
      index: index.html
      spa: true

  - name: myapp-service
    service_type: plugin
    plugin:
      name: plugin_sdk
      entry: myapp

  - name: plugin_nats
    service_type: plugin
    plugin:
      name: plugin_nats
      entry: myapp

middleware_groups:
  # Security & request metadata headers applied to most routes
  security:
    - plugin: RequestHeaderModifier
      payload:
        remove:
          - x-version
        set:
          - name: x-request-id
            value: "${uuid(v7)}"
          - name: x-forwarded-for
            value: "${request(client_ip)}"
          - name: x-host
            value: "${header(host)}"
          - name: x-timestamp
            value: "${timestamp()}"
    - plugin: ResponseHeaderModifier
      payload:
        set:
          - name: cache-control
            value: "no-store"
          - name: referrer-policy
            value: "no-referrer"
          - name: x-content-type-options
            value: "nosniff"
          - name: x-frame-options
            value: "DENY"
          - name: content-security-policy
            value: "default-src 'self'"
          - name: x-server
            value: ${or(env(SERVER_NAME), 'nylon-demo')}

  # Authorization example using FFI plugin
  auth:
    - plugin: plugin_sdk
      entry: "authz"
      payload:
        client_ip: "${request(client_ip)}"
        user_id: "${header(x-user-id)}"
  
  # Authorization example using NATS plugin (uncomment to use)
  # auth_nats:
  #   - plugin: plugin_nats
  #     entry: "authz"
  #     payload:
  #       client_ip: "${request(client_ip)}"
  #       user_id: "${header(x-user-id)}"
