http:
  - 0.0.0.0:8088
https:
  - 0.0.0.0:8443
metrics:
  - 127.0.0.1:6192
config_dir: "./examples/proxy"
acme: "./examples/acme"
pingora:
  # https://github.com/cloudflare/pingora/blob/main/docs/user_guide/daemon.md
  daemon: false
  # https://github.com/cloudflare/pingora/blob/main/docs/user_guide/conf.md
  grace_period_seconds: 1
  graceful_shutdown_timeout_seconds: 1

# WebSocket adapter configuration (optional)
# websocket:
#   adapter_type: redis  # memory | redis | cluster
#   redis:
#     host: "localhost"
#     port: 6379
#     password: null
#     db: 0
#     key_prefix: "nylon:ws"