http:
  - 0.0.0.0:8088
https:
  - 0.0.0.0:8443
metrics:
  - 127.0.0.1:6192
config_dir: "examples/proxy"
dispatcher: "./target/debug/libnylon_dispatcher.dylib"
database: "examples/db"
pingora:
  # https://github.com/cloudflare/pingora/blob/main/docs/user_guide/daemon.md
  daemon: false
  # https://github.com/cloudflare/pingora/blob/main/docs/user_guide/conf.md
  # threads: 10
  # upstream_keepalive_pool_size: 20
  # work_stealing: true
  # error_log: /var/log/pingora/error.log
  # pid_file: /run/pingora.pid
  # upgrade_sock: /tmp/pingora_upgrade.sock
  # user: nobody
  # group: webusers
  # ca_file: /etc/ssl/certs/ca-certificates.crt
  grace_period_seconds: 1
  graceful_shutdown_timeout_seconds: 1