[package]
name = "nylon-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
nylon-types = { path = "../../crates/nylon-types" }
nylon-error = { path = "../../crates/nylon-error" }
flatbuffers = { workspace = true }
pingora = { workspace = true }
bytes = { workspace = true }