// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nylon_plugin

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HeaderKeyValue struct {
	_tab flatbuffers.Table
}

func GetRootAsHeaderKeyValue(buf []byte, offset flatbuffers.UOffsetT) *HeaderKeyValue {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeaderKeyValue{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeaderKeyValueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeaderKeyValue(buf []byte, offset flatbuffers.UOffsetT) *HeaderKeyValue {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeaderKeyValue{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeaderKeyValueBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeaderKeyValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeaderKeyValue) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeaderKeyValue) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HeaderKeyValue) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HeaderKeyValueStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HeaderKeyValueAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func HeaderKeyValueAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func HeaderKeyValueEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
