// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nylon_plugin

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NylonHttpHeaders struct {
	_tab flatbuffers.Table
}

func GetRootAsNylonHttpHeaders(buf []byte, offset flatbuffers.UOffsetT) *NylonHttpHeaders {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NylonHttpHeaders{}
	x.Init(buf, n+offset)
	return x
}

func FinishNylonHttpHeadersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNylonHttpHeaders(buf []byte, offset flatbuffers.UOffsetT) *NylonHttpHeaders {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NylonHttpHeaders{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNylonHttpHeadersBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NylonHttpHeaders) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NylonHttpHeaders) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NylonHttpHeaders) Headers(obj *HeaderKeyValue, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *NylonHttpHeaders) HeadersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func NylonHttpHeadersStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NylonHttpHeadersAddHeaders(builder *flatbuffers.Builder, headers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(headers), 0)
}
func NylonHttpHeadersStartHeadersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NylonHttpHeadersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
