// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package nylon_plugin

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RemoveResponseHeader struct {
	_tab flatbuffers.Table
}

func GetRootAsRemoveResponseHeader(buf []byte, offset flatbuffers.UOffsetT) *RemoveResponseHeader {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RemoveResponseHeader{}
	x.Init(buf, n+offset)
	return x
}

func FinishRemoveResponseHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRemoveResponseHeader(buf []byte, offset flatbuffers.UOffsetT) *RemoveResponseHeader {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RemoveResponseHeader{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRemoveResponseHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RemoveResponseHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RemoveResponseHeader) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RemoveResponseHeader) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RemoveResponseHeaderStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RemoveResponseHeaderAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func RemoveResponseHeaderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
